"back"[
  "node_modules",
  "src"[
    "controller"["ride-confirm-controller","ride-estimate-controller","ride-history-controller"],
    "data"["connection.ts"],
    "error"["custom-error-DTO.ts"],
    "models"["driver.ts","ride-history.ts"],
    "repositories"["google-api-repository.ts"],
    "routes"["routes.ts"],
    "services"["driver-service.ts","history-service.ts","ride-confirm-service.ts","ride-estimate-service.ts", "ride-history-service.ts"],
    "types"["driver-type.ts","ride-confirm-types.ts","ride-estimate-types.ts", "ride-history-types.ts"],
    "server.ts"
  ],
  ".env",
  ".gitignore",
  "package-lock.json",
  "package.json",
  "tsconfig.json",
];
"front"[
  "node_modules",
  "src"[
    "components"["ride-confirm","ride-estimate","ride-history"],
    "App.tsx",
    "globals.css",
    "main.tsx",
    "vite-env.d.ts"
  ],"index.html",
  "README.md",
  "vite.config.ts",
  ".gitignore",
  "package-lock.json",
  "package.json",
  "tsconfig.json",
  "tsconfig.app.json",
  "tsconfig.node.json",
]